✨ 윤호 1주차 정리
Bom-FE/Bom-FE-study pull request #2
Opened 2023-02-27 09:47 UTC by munolee

- Cypress 활용 E2E 테스트 프로세스 도입에 대한 내용 정리

2023-02-28 12:49 UTC, jeehoo0767 requested changes
레퍼런스 줘요 !!

2023-02-28 12:51 UTC, wonjin-dev approved these changes
가능하다면 추가되면 좋겠어요 !!
- cypress만의 장점
- sorry-cypress 레퍼런스 주소
- github action에 위임 했을때 서버 키는건 어떻게 ?
- e2e로 이득본 사례

2023-02-28 12:52 UTC, jeehoo0767 approved these changes
e2e 테스트 도입을 통해 캐치했던 기억에 남는 이슈가 있다면 적어주면 좋을거 같아요 !

2023-03-09 06:21 UTC, munolee commented
> 레퍼런스 줘요 !!

https://fe-developers.kakaoent.com/2023/230209-e2e/#3-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%86%8D%EB%8F%84

2023-03-09 13:57 UTC, merged